algoritmo "Meu nome"

var //AREA DE DECLARAÇÃO DE VARIAVEIS

Nome:Caractere
data1, data2, subtrair:Inteiro

inicio

Escreva ("Digite seu Nome: ")
Leia (Nome)
Escreva ("Digite sua data de nascimento:")
Leia (data1)
Escreva ("Digite sua data atual ")
Leia (data2)
subtrair <- data2 - data1 //A variavel soma recebe a diferença da data2 subtraindo a data1
Escreval("Meu nome é ",Nome)
Escreva("A subtração entre ", data1," e ",data2," e a minha idade atual que é" ,subtrair ," anos")

fimalgoritmo
