algoritmo "MEDIAANOLETIVO"
// Função :
// Autor :
// Data : 17/08/2020
// Seção de Declarações
var
Nota1,Nota2,Nota3,Nota4,media:Real
inicio
Escreva ("Digite a nota da atividade 1?")
Leia(Nota1)
Escreva ("Digite a nota da atividade  2?")
Leia(Nota2)
Escreva ("Digite a nota da atividade 1?")
Leia(Nota3)
Escreva ("Digite a nota da atividade  2?")
Leia(Nota4)
media <- (Nota1+Nota2+Nota3+Nota4)/4
Escreva("A sua nota é:", media)

fimalgoritmo
